---
- name: Install 0G Validator Node
  hosts: localhost
  become: true

  vars_prompt:
    - name: moniker
      prompt: "Enter your node name"
      private: false

  vars:
    CHAIN_ID: "zgtendermint_16600-1"
    RPC_PORT: "26657"
    LOG_CONTRACT_ADDRESS: "0xb8F03061969da6Ad38f0a4a9f8a86bE71dA3c8E7"
    MINE_CONTRACT: "0x96D90AAcb2D5Ab5C69c1c351B0a0F105aae490bE"
    LOG_SYNC_START_BLOCK_NUMBER: 334797
    BLOCKCHAIN_RPC_ENDPOINT: "https://evm-rpc-0g.mflow.tech"
    SEEDS: "c4d619f6088cb0b24b4ab43a0510bf9251ab5d7f@54.241.167.190:26656,44d11d4ba92a01b520923f51632d2450984d5886@54.176.175.48:26656,f2693dd86766b5bf8fd6ab87e2e970d564d20aff@54.193.250.204:26656,f878d40c538c8c23653a5b70f615f8dccec6fb9f@54.215.187.94:26656"
    PERSISTENT_PEERS: "4e3e8e77c611fa847e884cde586d4f4e6831feca@95.111.235.24:12656,f4658b01d888072b35f6eb32a7ec8cb43b44ef4f@109.199.115.111:12656,32005f0fd9921e294c0f926a87f75da449425a38@31.220.80.90:12656,98f648e34eb32e5d4c94365b05c3ab5bcd608ef8@158.220.117.198:27656,3797f3e459b642a3613c91148ee526bbb5cf7983@62.171.137.244:12656,39dc4c1f8599f03e351c6fc3948fd948e77c3120@161.97.119.65:12656,0811975134ce6a2c9971eb2ac9bffe14e6be8860@164.68.116.131:12656,bb1293ddd974d872936b4a80aad8c98a427537aa@213.199.32.106:12656,cb0043118b2257a554f48276eefb1a5822ffad77@113.211.211.17:26656,2a3f876c65302d195b208d5ee5e5290c69e2bcb2@38.242.254.69:12656,671cb2b4ea3723873d32e5ff4930f3df12f90a20@185.135.137.36:12656,fb131213fc65843d63ade080f6fa0ae375acc479@38.242.222.77:26656,528ecac6f52bd79f30d0d15fb837d7b8750c22e9@80.76.43.54:26656,8b845cd6154ee7cc481180a624d4c00a62998cf0@38.242.246.98:12656,761717d770596322601536fa939ccd104a613a24@185.192.96.230:12656,a3d8d4966a284d8408887d22922548b40ec0f40a@161.97.120.0:12656,77af278955c67f579fdeeae8695e10007a9c48de@185.207.251.74:12656,9b09a6d82d53ec6ca353388515b66ec666bbb29b@173.249.29.128:12656,ace933d170c8b3dc7825033dac93a32ec0e54b32@213.199.32.102:12656,21a064ed7e911bbaac680b8b1b94d8cd99fbc9fb@161.97.123.17:12656,32f09ef793141363e36cf79cdc758793c23e3e20@31.220.80.76:12656,1469b5aba1c6401bc191fa5a6fabbc6e02720add@62.171.156.121:12656,df5c2c8d3d3f037317776aa1c8f17b78895e78e6@75.119.131.191:12656,8d9e1048a149e31bb038b6cc41f4beb412593a3d@62.171.132.182:12656,8c0141c67ae2feff05915cd2eb2f99255d62f562@109.199.115.112:12656,025cc5990c4e92b172e3f54e74aad2734496490f@109.199.115.26:12656,ee0f3fef550162af480fa68059146ec171a879a1@31.220.80.88:12656,48f0d1b942f2aca69dac8507fd18252254b95322@109.199.114.19:12656,fb1da66e04e2ff473c38faf98efce14f4cabda64@94.250.202.154:12656,4966d1345931eb521bbcf59ff6acb200686d1d9e@109.199.115.113:12656,83b45c4f6e4a4073884a1baf08db13d6b808418b@185.217.126.196:12656,614f9b12e0fd545c402d486ebd011616218cce29@155.133.26.142:12656,628e8041a65a7de9d3c364992667d056be562c85@149.102.137.159:12656,a511a2f131138fd93d4237a28485aa92c2d0b111@62.171.164.86:12656,49a9ccd19e980b180cd81df1876d255882f58eec@38.242.251.63:12656,99db6ad1d2a1a4e2d01f4adadd80365d18968427@109.123.242.162:12656,44d54579a90f49175558ff0ca749e0da3a1be098@109.199.114.20:12656,f170627b872fd09585de6611975558536c060a78@5.189.141.14:12656,1bcdba097b455c95cc075447a0c38dc0241f7e58@109.123.246.148:12656,bdcd655ef5ec1cc27303b9db3b2b85c8be07145e@161.97.86.234:12656,94f229e213cefb87a4fb7ec07b34bb076e31ec34@207.180.206.141:12656,0a111c938a9c6c8a9426401fa2cb66868474ebd0@38.242.212.60:12656,d0fb53901f49d9a9946f4b1039f4c59d63a7beda@173.249.53.171:12656,5fb1e65e22625e82ef7e8c7a380ccc3f24ef616c@217.76.57.109:12656,dd4de14ae0f6d21b8e4a9b2033c8627b086bd895@65.109.37.171:12656,eccdf5d52821a50b9e89b93e2d330a78fecca81f@156.67.81.83:12656,5d57e81a8bdd9412b761655a27546320b45bb4cd@156.67.81.89:12656,0c2566803d4be493dba2329e7e8302bbc0dd01c5@109.199.115.117:12656,9a71b878aedb6c1f9762a978bc4399160590cee9@213.199.51.35:12656,252a93bca0aef16fecae74aba9ab6b96ab668c4c@89.116.27.77:12656"
    SNAPSHOT_URL: "https://rpc-zero-gravity-testnet.trusted-point.com/latest_snapshot.tar.lz4"
    HOME_DIR: "{{ ansible_env.HOME }}/.0gchain"

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - curl
          - git
          - jq
          - build-essential
          - gcc
          - unzip
          - wget
          - lz4

    - name: Install Go
      ansible.builtin.shell: |
        cd $HOME
        ver="1.22.3"
        wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
        rm "go$ver.linux-amd64.tar.gz"
        echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
        source ~/.bash_profile
        go version
      args:
        executable: /bin/bash

    - name: Build 0gchaind binary
      ansible.builtin.git:
        repo: 'https://github.com/0glabs/0g-chain.git'
        dest: "{{ ansible_env.HOME }}/0g-chain"
        version: "v0.1.0"

    - name: Compile 0gchaind
      ansible.builtin.shell: |
        cd {{ ansible_env.HOME }}/0g-chain
        make install
        0gchaind version
      args:
        executable: /bin/bash

    - name: Initialize the node
      ansible.builtin.shell: |
        0gchaind init {{ moniker }} --chain-id {{ CHAIN_ID }}
        0gchaind config chain-id {{ CHAIN_ID }}
        0gchaind config node tcp://localhost:{{ RPC_PORT }}
        0gchaind config keyring-backend os
      args:
        executable: /bin/bash

    - name: Download genesis.json
      ansible.builtin.get_url:
        url: "https://github.com/0glabs/0g-chain/releases/download/v0.1.0/genesis.json"
        dest: "{{ HOME_DIR }}/config/genesis.json"

    - name: Add seeds to config.toml
      ansible.builtin.shell: |
        sed -i.bak -e "s/^seeds *=.*/seeds = \"{{ SEEDS }}\"/" {{ HOME_DIR }}/config/config.toml
      args:
        executable: /bin/bash

    - name: Add persistent peers to config.toml
      ansible.builtin.shell: |
        sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"{{ PERSISTENT_PEERS }}\"/" {{ HOME_DIR }}/config/config.toml
      args:
        executable: /bin/bash

    - name: Change ports (Optional)
      ansible.builtin.shell: |
        EXTERNAL_IP=$(wget -qO- eth0.me)
        PROXY_APP_PORT=26658
        P2P_PORT=26656
        PPROF_PORT=6060
        API_PORT=1317
        GRPC_PORT=9090
        GRPC_WEB_PORT=9091
        RPC_PORT=26657
        sed -i \
            -e "s/\(proxy_app = \"tcp:\/\/\)\([^:]*\):\([0-9]*\).*/\1\2:$PROXY_APP_PORT\"/" \
            -e "s/^laddr = \".*/laddr = \"tcp:\/\/localhost:$RPC_PORT\"/" \
            -e "s/\(pprof_laddr = \"\)\([^:]*\):\([0-9]*\).*/\1localhost:$PPROF_PORT\"/" \
            -e "/\[p2p\]/,/^\[/{s/\(laddr = \"tcp:\/\/\)\([^:]*\):\([0-9]*\).*/\10.0.0.0:$P2P_PORT\"/}" \
            -e "/\[p2p\]/,/^\[/{s/\(external_address = \"\)\([^:]*\):\([0-9]*\).*/\1${EXTERNAL_IP}:$P2P_PORT\"/; t; s/\(external_address = \"\).*/\1${EXTERNAL_IP}:$P2P_PORT\"/}" \
            $HOME/.0gchain/config/config.toml
        sed -i \
            -e "/\[api\]/,/^\[/{s/\(address = \"tcp:\/\/\)\([^:]*\):\([0-9]*\)\(\".*\)/\1\2:$API_PORT\4/}" \
            -e "/\[grpc\]/,/^\[/{s/\(address = \"\)\([^:]*\):\([0-9]*\)\(\".*\)/\1\2:$GRPC_PORT\4/}" \
            -e "/\[grpc-web\]/,/^\[/{s/\(address = \"\)\([^:]*\):\([0-9]*\)\(\".*\)/\1\2:$GRPC_WEB_PORT\4/}" \
            $HOME/.0gchain/config/app.toml
      args:
        executable: /bin/bash

    - name: Configure EVM RPC and WebSocket addresses
      ansible.builtin.shell: |
        sed -i 's/^address = "127.0.0.1:8545"/address = "0.0.0.0:8545"/' {{ HOME_DIR }}/config/app.toml
        sed -i 's/^ws-address = "127.0.0.1:8546"/ws-address = "0.0.0.0:8546"/' {{ HOME_DIR }}/config/app.toml
      args:
        executable: /bin/bash

    - name: Configure pruning to save storage (Optional)
      ansible.builtin.shell: |
        sed -i \
            -e "s/^pruning *=.*/pruning = \"custom\"/" \
            -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"100\"/" \
            -e "s/^pruning-interval *=.*/pruning-interval = \"10\"/" \
            "$HOME/.0gchain/config/app.toml"
      args:
        executable: /bin/bash

    - name: Set min gas price
      ansible.builtin.shell: |
        sed -i "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0ua0gi\"/" $HOME/.0gchain/config/app.toml
      args:
        executable: /bin/bash

    - name: Enable indexer (Optional)
      ansible.builtin.shell: |
        sed -i "s/^indexer *=.*/indexer = \"kv\"/" $HOME/.0gchain/config/config.toml
      args:
        executable: /bin/bash

    - name: Ensure fs.inotify.max_user_instances is set to 256
      ansible.builtin.sysctl:
        name: fs.inotify.max_user_instances
        value: 256
        state: present
        reload: yes    

    - name: Increase the limit of open files
      ansible.builtin.lineinfile:
        path: /etc/security/limits.conf
        line: "* soft nofile 65535\n* hard nofile 65535"
        create: yes

    - name: Set DefaultLimitNOFILE in systemd configuration
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        line: "DefaultLimitNOFILE=65535"
        create: yes

    - name: Set DefaultLimitNOFILE in user systemd configuration
      ansible.builtin.lineinfile:
        path: /etc/systemd/user.conf
        line: "DefaultLimitNOFILE=65535"
        create: yes

    - name: Reload systemd daemon
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl restart systemd-logind
      args:
        executable: /bin/bash

    - name: Create systemd service file for 0G Validator Node
      ansible.builtin.template:
        src: templates/0gd-node.service.j2
        dest: /etc/systemd/system/0gd-node.service

    - name: Enable and start 0G Validator Node service
      ansible.builtin.systemd:
        name: 0gd-node
        enabled: true
        state: started

    - name: Download latest snapshot
      ansible.builtin.get_url:
        url: "{{ SNAPSHOT_URL }}"
        dest: "{{ ansible_env.HOME }}/latest_snapshot.tar.lz4"

    - name: Stop 0G Validator Node service
      ansible.builtin.systemd:
        name: 0gd-node
        state: stopped

    - name: Backup priv_validator_state.json
      ansible.builtin.shell: |
        cp {{ HOME_DIR }}/data/priv_validator_state.json {{ HOME_DIR }}/priv_validator_state.json.backup
      args:
        executable: /bin/bash

    - name: Reset tendermint state
      ansible.builtin.shell: |
        0gchaind tendermint unsafe-reset-all --home {{ HOME_DIR }} --keep-addr-book
      args:
        executable: /bin/bash

    - name: Extract snapshot
      ansible.builtin.shell: |
        lz4 -d -c {{ ansible_env.HOME }}/latest_snapshot.tar.lz4 | tar -xf - -C {{ HOME_DIR }}
      args:
        executable: /bin/bash

    - name: Restore priv_validator_state.json
      ansible.builtin.shell: |
        mv {{ HOME_DIR }}/priv_validator_state.json.backup {{ HOME_DIR }}/data/priv_validator_state.json
      args:
        executable: /bin/bash

    - name: Restart 0G Validator Node service
      ansible.builtin.systemd:
        name: 0gd-node
        state: restarted

    - name: Monitor 0G Validator Node service
      ansible.builtin.shell: |
        sudo journalctl -u 0gd-node -f -o cat
      args:
        executable: /bin/bash
