---
- name: Install 0G Validator Node
  hosts: localhost
  become: true

  vars_prompt:
    - name: moniker
      prompt: "Enter your node name"
      private: false

  vars:
    CHAIN_ID: "zgtendermint_16600-2"
    KEYRING_BACKEND: "os"
    RPC_PORT: "26657"
    SEEDS: "59df4b3832446cd0f9c369da01f2aa5fe9647248@162.55.65.137:27956"
    PERSISTENT_PEERS: "6dbb0450703d156d75db57dd3e51dc260a699221@152.53.47.155:13456,df4cc52fa0fcdd5db541a28e4b5a9c6ce1076ade@37.60.246.110:13456,54c269f44e1a9c3fd00fe62db52ac08e59b148f7@85.239.232.29:13456,dbfb5240845c8c7d2865a35e9f361cc42877721f@78.46.40.246:34656,386c82b09e0ec6a68e653a5d6c57f766ae73e0df@194.163.183.208:26656,d5e294d6d5439f5bd63d1422423d7798492e70fd@77.237.232.146:26656,48e3cab55ba7a1bc8ea940586e4718a857de84c4@178.63.4.186:26656,3bd6c0c825470d07cd49e57d0b650d490cc48527@37.60.253.166:26656,6efd3559f5d9d13e6442bc2fc9b17e50dc800970@91.205.104.91:13456,3b3ddcd4de429456177b29e5ca0febe4f4c21989@75.119.139.198:26656,58702cc91cc456e9beeb9b3e381f23fac39a3311@94.16.31.30:13456,e7c8f15c88ec1d6dc2b3a9ab619519fbd61182d6@217.76.54.13:26656,7e6124b7816c2fddd1e0f08bbaf0b6876230c5f4@37.27.120.13:26656,d82f58230074dccc8371f05df35c3e8d71ece034@69.67.150.107:23656,537abd857a3335e46e0f010cc01bde94854691a4@5.252.55.236:13456"
    SNAPSHOT_URL: "https://snapshots-testnet.nodejumper.io/0g-testnet/0g-testnet_latest.tar.lz4"
    HOME_DIR: "{{ ansible_env.HOME }}/.0gchain"


  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: yes
        name:
          - curl
          - snapd
          - git
          - jq
          - build-essential
          - gcc
          - unzip
          - wget
          - lz4

    - name: Install Go
      ansible.builtin.shell: |
        wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
        echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bash_profile
      args:
        executable: /bin/bash

    - name: Set timezone to UTC
      ansible.builtin.command:
        cmd: timedatectl set-timezone UTC

    - name: Clone 0G chain repository
      ansible.builtin.git:
        repo: 'https://github.com/0glabs/0g-chain.git'
        dest: "{{ ansible_env.HOME }}/0g-chain"
        version: "v0.2.3"

    - name: Run install script
      ansible.builtin.shell: |
        cd {{ ansible_env.HOME }}/0g-chain/networks/testnet
        ./install.sh
      args:
        executable: /bin/bash

    - name: Source profile
      ansible.builtin.shell: |
        source $HOME/.profile
      args:
        executable: /bin/bash

    - name: Set Chain ID
      ansible.builtin.shell: |
        0gchaind config chain-id {{ CHAIN_ID }}
      args:
        executable: /bin/bash

    - name: Initialize the node
      ansible.builtin.shell: |
        0gchaind init {{ moniker }} --chain-id {{ CHAIN_ID }}
      args:
        executable: /bin/bash

    - name: Set keyring-backend
      ansible.builtin.shell: |
        0gchaind config keyring-backend {{ KEYRING_BACKEND }}
      args:
        executable: /bin/bash   

    - name: Download genesis.json
      ansible.builtin.shell: |
        sudo apt install -y unzip wget
        rm ~/.0gchain/config/genesis.json
        wget -P ~/.0gchain/config https://github.com/0glabs/0g-chain/releases/download/v0.2.3/genesis.json
      args:
        executable: /bin/bash

    - name: Validate genesis file
      ansible.builtin.shell: |
        0gchaind validate-genesis
      args:
        executable: /bin/bash

    - name: Add seeds to config.toml
      ansible.builtin.shell: |
        sed -i.bak -e "s/^seeds *=.*/seeds = \"{{ SEEDS }}\"/" {{ ansible_env.HOME }}/.0gchain/config/config.toml
      args:
        executable: /bin/bash

    - name: Add persistent peers to config.toml
      ansible.builtin.shell: |
        sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"{{ PERSISTENT_PEERS }}\"/" {{ ansible_env.HOME }}/.0gchain/config/config.toml
      args:
        executable: /bin/bash

    - name: Change ports (Optional)
      ansible.builtin.shell: |
        EXTERNAL_IP=$(wget -qO- eth0.me)
        PROXY_APP_PORT=26658
        P2P_PORT=26656
        PPROF_PORT=6060
        API_PORT=1317
        GRPC_PORT=9090
        GRPC_WEB_PORT=9091
        RPC_PORT=26657
        sed -i \
            -e "s/\(proxy_app = \"tcp:\/\/\)\([^:]*\):\([0-9]*\).*/\1\2:$PROXY_APP_PORT\"/" \
            -e "s/^laddr = \".*/laddr = \"tcp:\/\/0.0.0.0:$RPC_PORT\"/" \
            -e "s/\(pprof_laddr = \"\)\([^:]*\):\([0-9]*\).*/\1localhost:$PPROF_PORT\"/" \
            -e "/\[p2p\]/,/^\[/{s/\(laddr = \"tcp:\/\/\)\([^:]*\):\([0-9]*\).*/\10.0.0.0:$P2P_PORT\"/}" \
            -e "/\[p2p\]/,/^\[/{s/\(external_address = \"\)\([^:]*\):\([0-9]*\).*/\1${EXTERNAL_IP}:$P2P_PORT\"/; t; s/\(external_address = \"\).*/\1${EXTERNAL_IP}:$P2P_PORT\"/}" \
            $HOME/.0gchain/config/config.toml
        sed -i \
            -e "/\[api\]/,/^\[/{s/\(address = \"tcp:\/\/\)\([^:]*\):\([0-9]*\)\(\".*\)/\1\2:$API_PORT\4/}" \
            -e "/\[grpc\]/,/^\[/{s/\(address = \"\)\([^:]*\):\([0-9]*\)\(\".*\)/\1\2:$GRPC_PORT\4/}" \
            -e "/\[grpc-web\]/,/^\[/{s/\(address = \"\)\([^:]*\):\([0-9]*\)\(\".*\)/\1\2:$GRPC_WEB_PORT\4/}" \
            $HOME/.0gchain/config/app.toml
      args:
        executable: /bin/bash

    - name: Configure EVM RPC and WebSocket addresses
      ansible.builtin.shell: |
        sed -i 's/^address = "127.0.0.1:8545"/address = "0.0.0.0:8545"/' {{ ansible_env.HOME }}/.0gchain/config/app.toml
        sed -i 's/^ws-address = "127.0.0.1:8546"/ws-address = "0.0.0.0:8546"/' {{ ansible_env.HOME }}/.0gchain/config/app.toml
      args:
        executable: /bin/bash

    - name: Configure pruning to save storage (Optional)
      ansible.builtin.shell: |
        sed -i \
            -e "s/^pruning *=.*/pruning = \"custom\"/" \
            -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"100\"/" \
            -e "s/^pruning-interval *=.*/pruning-interval = \"10\"/" \
            "$HOME/.0gchain/config/app.toml"
      args:
        executable: /bin/bash

    - name: Set min gas price
      ansible.builtin.shell: |
        sed -i "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0ua0gi\"/" $HOME/.0gchain/config/app.toml
      args:
        executable: /bin/bash

    - name: Enable indexer (Optional)
      ansible.builtin.shell: |
        sed -i "s/^indexer *=.*/indexer = \"kv\"/" $HOME/.0gchain/config/config.toml
      args:
        executable: /bin/bash

    - name: Ensure fs.inotify.max_user_instances is set to 256
      ansible.builtin.sysctl:
        name: fs.inotify.max_user_instances
        value: 256
        state: present
        reload: yes    

    - name: Increase the limit of open files
      ansible.builtin.lineinfile:
        path: /etc/security/limits.conf
        line: "* soft nofile 65535\n* hard nofile 65535"
        create: yes

    - name: Set DefaultLimitNOFILE in systemd configuration
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        line: "DefaultLimitNOFILE=65535"
        create: yes

    - name: Set DefaultLimitNOFILE in user systemd configuration
      ansible.builtin.lineinfile:
        path: /etc/systemd/user.conf
        line: "DefaultLimitNOFILE=65535"
        create: yes

    - name: Reload systemd daemon
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl restart systemd-logind
      args:
        executable: /bin/bash

    - name: Create systemd service file for 0G Validator Node
      ansible.builtin.template:
        src: templates/0gd-node.service.j2
        dest: /etc/systemd/system/0gd-node.service

    - name: Enable and start 0G Validator Node service
      ansible.builtin.systemd:
        name: 0gd-node
        enabled: true
        state: started

    #- name: Download latest snapshot
    #  ansible.builtin.get_url:
    #    url: "{{ SNAPSHOT_URL }}"
    #    dest: "{{ ansible_env.HOME }}/latest_snapshot.tar.lz4"

    #- name: Stop 0G Validator Node service
    #  ansible.builtin.systemd:
    #    name: 0gd-node
    #    state: stopped    

    #- name: Backup priv_validator_state.json
    #  ansible.builtin.shell: |
    #    cp {{ HOME_DIR }}/data/priv_validator_state.json {{ HOME_DIR }}/priv_validator_state.json.backup
    #  args:
    #    executable: /bin/bash

    #- name: Reset tendermint state
    #  ansible.builtin.shell: |
    #    0gchaind tendermint unsafe-reset-all --home {{ HOME_DIR }} --keep-addr-book
    #  args:
    #    executable: /bin/bash

    #- name: Extract snapshot
    #  ansible.builtin.shell: |
    #    lz4 -d -c {{ ansible_env.HOME }}/latest_snapshot.tar.lz4 | tar -xf - -C {{ HOME_DIR }}
    #  args:
    #    executable: /bin/bash

    #- name: Restore priv_validator_state.json
    #  ansible.builtin.shell: |
    #    mv {{ HOME_DIR }}/priv_validator_state.json.backup {{ HOME_DIR }}/data/priv_validator_state.json
    #  args:
    #    executable: /bin/bash

    #- name: start 0G Validator Node service
    #  ansible.builtin.systemd:
    #    name: 0gd-node
    #    state: started


