---
- name: Register 0G Validator Node
  hosts: localhost
  become: true

  vars_prompt:
    - name: wallet_name
      prompt: "Enter your wallet name"
      private: false
    - name: moniker
      prompt: "Enter your node name"
      private: false

  vars:
    CHAIN_ID: "zgtendermint_16600-1"
    KEYRING_BACKEND: "test"

  tasks:
    - name: Ensure node is fully synced
      ansible.builtin.command:
        cmd: 0gchaind status
      register: node_status
      until: "{{ (node_status.stdout | from_json).sync_info.catching_up == false }}"
      retries: 5
      delay: 60

    - name: Get wallet address
      ansible.builtin.command:
        cmd: 0gchaind keys show {{ wallet_name }} -a --keyring-backend {{ KEYRING_BACKEND }}
      register: wallet_address

    - name: Check wallet balance
      ansible.builtin.command:
        cmd: 0gchaind q bank balances {{ wallet_address.stdout }}
      register: wallet_balance

    - name: Display wallet balance
      ansible.builtin.debug:
        msg: "Wallet balance: {{ wallet_balance.stdout }}"

    - name: Create validator
      ansible.builtin.shell: |
        0gchaind tx staking create-validator \
          --amount=1000000ua0gi \
          --pubkey=$(0gchaind tendermint show-validator) \
          --moniker={{ moniker }} \
          --chain-id={{ CHAIN_ID }} \
          --commission-rate=0.05 \
          --commission-max-rate=0.10 \
          --commission-max-change-rate=0.01 \
          --min-self-delegation=1 \
          --from={{ wallet_name }} \
          --identity="" \
          --website="" \
          --details="I like 0G project" \
          --gas=auto \
          --gas-adjustment=1.4 \
          --keyring-backend {{ KEYRING_BACKEND }} \
          -y
      register: validator_creation

    - name: Display validator creation output
      ansible.builtin.debug:
        msg: "{{ validator_creation.stdout }}"

    - name: Delegate tokens
      ansible.builtin.shell: |
        0gchaind tx staking delegate $(0gchaind keys show {{ wallet_name }} --bech val -a --keyring-backend {{ KEYRING_BACKEND }}) 1000000ua0gi --from {{ wallet_name }} --keyring-backend {{ KEYRING_BACKEND }} -y
      register: delegation

    - name: Display delegation output
      ansible.builtin.debug:
        msg: "{{ delegation.stdout }}"

    - name: Query validator state
      ansible.builtin.shell: |
        0gchaind q staking validator $(0gchaind keys show {{ wallet_name }} --bech val -a --keyring-backend {{ KEYRING_BACKEND }})
      register: validator_state

    - name: Display validator state
      ansible.builtin.debug:
        msg: "{{ validator_state.stdout }}"
