---
- name: Register 0G Validator Node
  hosts: localhost
  become: true

  vars_prompt:
    - name: wallet_name
      prompt: "Enter your wallet name"
      private: false
    - name: moniker
      prompt: "Enter your node name"
      private: false

  vars:
    CHAIN_ID: "zgtendermint_16600-1"

  tasks:
    - name: Ensure node is fully synced
      ansible.builtin.command:
        cmd: 0gchaind status
      register: node_status
      until: "node_status.stdout | from_json | json_query('SyncInfo.catching_up') == false"
      retries: 5
      delay: 60

    - name: Check wallet balance
      ansible.builtin.command:
        cmd: 0gchaind q bank balances $(0gchaind keys show {{ wallet_name }} -a)
      register: wallet_balance

    - name: Display wallet balance
      ansible.builtin.debug:
        msg: "Wallet balance: {{ wallet_balance.stdout }}"

    - name: Create validator
      ansible.builtin.shell: |
        0gchaind tx staking create-validator \
          --amount=1000000ua0gi \
          --pubkey=$(0gchaind tendermint show-validator) \
          --moniker={{ moniker }} \
          --chain-id={{ CHAIN_ID }} \
          --commission-rate=0.05 \
          --commission-max-rate=0.10 \
          --commission-max-change-rate=0.01 \
          --min-self-delegation=1 \
          --from={{ wallet_name }} \
          --identity="" \
          --website="" \
          --details="0G to the moon!" \
          --gas=500000 --gas-prices=99999ua0gi \
          -y
      register: validator_creation

    - name: Display validator creation output
      ansible.builtin.debug:
        msg: "{{ validator_creation.stdout }}"
